# Generated by Django 5.1.2 on 2024-10-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='orders',
        ),
        migrations.AddField(
            model_name='orders',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
            preserve_default=False,
        ),
    ]
