# Generated by Django 5.1.2 on 2024-10-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products_menu',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products_menu',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.RemoveField(
            model_name='users',
            name='img',
        ),
        migrations.RemoveField(
            model_name='users',
            name='orders',
        ),
        migrations.AddField(
            model_name='orders',
            name='item_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
