# Generated by Django 5.1.2 on 2024-10-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_orders_orders_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itemmenu',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='users',
        ),
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='orders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
