# Generated by Django 5.1.2 on 2024-10-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_discription_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
